// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/mini-games": {
    params: {};
  };
  "/study": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/dashboard" | "/mini-games" | "/study";
  };
  "routes/admin/admin-layout.tsx": {
    id: "routes/admin/admin-layout";
    page: "/dashboard" | "/mini-games" | "/study";
  };
  "routes/admin/dashboard.tsx": {
    id: "routes/admin/dashboard";
    page: "/dashboard";
  };
  "routes/admin/mini-games.tsx": {
    id: "routes/admin/mini-games";
    page: "/mini-games";
  };
  "routes/admin/study.tsx": {
    id: "routes/admin/study";
    page: "/study";
  };
};